# Generated by Django 3.0.2 on 2020-01-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_state', models.CharField(max_length=255)),
                ('reassignment_count', models.IntegerField()),
                ('reopen_count', models.IntegerField()),
                ('sys_mod_count', models.IntegerField()),
                ('contact_type', models.CharField(max_length=255)),
                ('location', models.IntegerField()),
                ('category', models.IntegerField()),
                ('subcategory', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predic', models.CharField(max_length=255)),
                ('prediction_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Prediction')),
            ],
        ),
    ]
